### ISSUE TITLE
Separate license file from readme

### ISSUE THREAD

**Issue by djmattyg007** [shazow/unstdlib.py#41]
It would be really nice if you could separate out the license portion of the readme file into a separate file. This would make the code a lot easier to package. At present I have to manually parse and extract the license from the readme in order to maintain a package in the Arch User Repository:

https://aur.archlinux.org/packages/python-unstdlib/

**Comment by shazow** [comment]
Ah cool, didn't know anyone actually packaged this. :) Sure, I'll add a LICENSE file.

**Comment by djmattyg007** [comment]
Wow, that's the fastest I've ever seen anyone respond to an issue. Thanks!

It's quite common on Arch for PyPi modules to be packaged like that. It makes it easier to track files, remove the package and check for updates.

**Comment by shazow** [comment]
:) Happy to help.

Fwiw, the spirit of unstdlib.py is for a bunch of different people to make their own versions of it, so there shouldn't necessarily be one de-facto standard one you can reuse across different peoples' projects. Might not be the best candidate for packaging, but use your judgement.
