### ISSUE TITLE
'basestring' class removed from Python 3

### ISSUE THREAD

**Issue by sleibrock** [shazow/unstdlib.py#48]
https://github.com/shazow/unstdlib.py/blob/master/unstdlib/html.py#L85

Ran across this error when using Python 3 code. We could modify it by checking for the Python version and linking `str` to the name `basestring` instead. Something like:

```python
from sys import version as sys_version
if sys_version[0] == "3":
  basestring = str
```

**Comment by shazow** [comment]
Fixed in https://github.com/shazow/unstdlib.py/commit/f894f58a6c69916e799c672dd3b1589c38fb130f

**Comment by shazow** [comment]
FYI released https://pypi.org/manage/project/unstdlib/release/1.7.1/ that should include the fix.
